### ISSUE TITLE
Add support for symbols in variable names

### ISSUE THREAD

**Issue by GuiltyDolphin** [granule-project/granule#116]
- support symbols (e.g., '+') in variable names
- support Agda/Haskell-style fixity declarations

Exception: it might be worth disallowing underscores, in case we decide to follow an Agda-style argument positional system in the future.

**Comment by buggymcbugfix** [comment]
I don't think this is a priority for us at the moment, but feel free to implement.

**Comment by buggymcbugfix** [comment]
Please add this under Projects above
