### ISSUE TITLE
Ill-graded composition functions typechecks

### ISSUE THREAD

**Issue by josefs** [granule-project/granule#123]
Here are a couple of composition functions which have bogus grades but still type checks:

```
comp : forall {a : Type,  b : Type, c : Type,  n : Nat }
     . (b -> c)[n] -> (a -> b)[n] -> (a -> c)[n]
comp [f] [g] = [\x -> f (g x)]

compaff : forall {a : Type,  b : Type, c : Type, m  n : Nat }
        . (b -> c)[0..n] -> (a -> b)[0..n] -> (a -> c)[0..n]
compaff [f] [g] = [\x -> f (g x)]

compinf : forall {a : Type,  b : Type, c : Type,  n : Nat }
        . (b[∞] -> c[∞])[n] -> (a -> b[∞])[n] -> (a -> c[∞])[n]
compinf [f] [g] = [\x -> f (g x)]
```

**Comment by buggymcbugfix** [comment]
I'm looking at this now and it seems fine. Sorry I was a bit confused yesterday. I will have a closer look after work.

**Comment by heades** [comment]
Yeah, these are okay.  For example, in the first case `comp` promotes the composition to `n`, and thus, the grades on `f` and `g` are really `1`, and so, during the promotion `1` gets multiplied by `n` resulting in `1 * n = n`.  This is why it works.  The others have similar reasoning.  Promotion can be tricky to think about.

**Comment by buggymcbugfix** [comment]
Ok, so after looking at this I can confirm that your `comp` is fine, @josefs. Note that you can be polymorphic over the coeffect:

~~~ granule
compose
  : forall {a : Type,  b : Type, c : Type, r : Coeffect, k : r }
  . (b -> c) [k] -> (a -> b) [k] -> (a -> c) [k]
compose [f] [g] = [\x -> f (g x)]
~~~

This subsumes your `comp`, `compaff` and `compinf`.

Example:

~~~ granule
data Apa = MkApa
data Bepa = MkBepa
data Cepa = MkCepa

f : (Bepa -> Cepa) []
f = [\MkBepa -> MkCepa]

g : (Apa -> Bepa) []
g = [\MkApa -> MkBepa]

fafterg : (Apa -> Cepa) []
fafterg = f ∘ g
~~~

PS: The `∘` operator just resolves to any function named `compose`. If you
`import Prelude`, you will probably want to rename the `compose` defined there.

**Comment by heades** [comment]
Very nice, and it type checks for the reasons I was saying; every coeffect has a unit.

**Comment by josefs** [comment]
Great, thanks for the detailed responses!
