### ISSUE TITLE
Approximation with intervals bug

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#136]
James just found this one:
```
import Choice 
b : Int [1..1] -> Int [0..1] -> Int
b [y] [z] = choose1 (choice [y] [z]) + y
```
(in `dev-minor`). Looks like some problem with compiling interval constraints. The first parameter should be of type `1..2` at least.

**Comment by dorchard** [comment]
Addendum, other programs involving intervals don't have this issue, e.g. 
```
smaller : Int [1..3] -> Int
smaller [x] = x + x + x + x
```
This is correctly rejected by the type checker

**Comment by heades** [comment]
Perhaps a problem with unit?

**Comment by dorchard** [comment]
Hmm, but then the second example would be failing too..
