### ISSUE TITLE
Release notes have a broken link

### ISSUE THREAD

**Issue by cogumbreiro** [granule-project/granule#183]
Hi, everyone,

You might be aware of this already, but I found a broken link in the following release notes:

https://github.com/granule-project/granule/releases/tag/v0.9.0.0

```
LNL semiring (Zero, One, Many) recovers linear logic via new hsup operation
to control 'push' behaviour on tensors. See: https://granule-project.github.io/papers/tlla_2021_paper11.pdf
```

Is this the right link?

https://hal-lirmm.ccsd.cnrs.fr/TLLA2021/lirmm-03271465

**Comment by dorchard** [comment]
Thanks @cogumbreiro! Fixed!
