### ISSUE TITLE
Polymorphism when deriving drop allows discarding arbitrary values

### ISSUE THREAD

**Issue by starsandspirals** [granule-project/granule#188]
```
impossible : Handle R -> ()
impossible x = drop@(Handle R) x
```

This function typechecks (incorrectly, but this problem is already known, see https://github.com/granule-project/granule/issues/175) but attempting to use it to drop a handle at runtime throws an exception.

However, this function:

```
impossible : forall {a : Type} . a -> ()
impossible x = drop@a x
```

*also* typechecks, but in this case *succeeds* at runtime regardless of the type `a`, allowing things such as file handles and arrays to be dropped even though this is unsound behaviour.

**Comment by dorchard** [comment]
Fixed by PR https://github.com/granule-project/granule/pull/220
