### ISSUE TITLE
Why is clone/copy not allowed to return an unique value

### ISSUE THREAD

**Issue by atennapel** [granule-project/granule#207]
Hello, I wasn't sure where to ask general questions about this project and the papers related to it, so I will just ask my question here :)
I was reading ["Linearity and Uniqueness: An Entente Cordiale"](https://granule-project.github.io/papers/esop22-paper.pdf) (nice paper btw!) and I was wondering why clone/copy is not allowed to return the unique value.

If I write `clone t as x in x` with expected type `!a -> *a`, then what can go wrong? If I clone an unrestricted value then the resulting value is unique right?

**Comment by atennapel** [comment]
This was answered by @starsandspirals. In the follow-up paper "Functional Ownership through Fractional Uniqueness" this restriction is lifted and the `copy` (the equivalent to `clone`) can return any return type.

**Comment by dorchard** [comment]
Indeed! Thanks @atennapel
