### ISSUE TITLE
Docker image missing StdLib

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#221]
It seems the Docker is missing StdLib, or at least the configuration to point to the StdLib (see https://github.com/granule-project/granule/blob/main/README.md#setting-the-path)

**Comment by raehik** [comment]
I can add StdLib, but now my Docker image apparently doesn't support UTF-8, so `:m Vec.gr` fails. Needs a bit more looking. See: https://github.com/granule-project/granule/pull/222

**Comment by raehik** [comment]
Sorted it in #222 -- added StdLib and pre-pointed `grepl` to it for the container.
