### ISSUE TITLE
Security is broken

### ISSUE THREAD

**Issue by thwfhk** [granule-project/granule#223]
The security (`Public` and `Private`) is broken, as we can write the following well-typed `leak` function.

```
leak : forall {a : Type} . a [Private] -> a [Public]
leak x = join (split x)

split : forall {a : Type} . a [Private] -> (a [Private]) [Public]
split [x] = [[x]]

join : forall {a : Type} . (a [Private]) [Public] -> a [Public]
join [[x]] = [x]
```

Fortunately, seems that this is just a bug of the implementation, instead of a bug of the semiring. I would expect `join` to be ill-typed as in the semiring `Private * Public = Private`, but obviously something went wrong during type checking.

**Comment by dorchard** [comment]
Thanks! I have opened a PR with the fix. This was an unfortunate conflation between two different semirings when it comes to how double unboxing behaves (which is what happens in `join`). This should have been defined as the multiplication for `Sec`, which it now is in this PR.

**Comment by thwfhk** [comment]
I see! Thank you.

**Comment by dorchard** [comment]
Fixed in `dev-minor` now. We will make a release with this in at some point!
