### ISSUE TITLE
Disallow repeated variables in patterns (non-linear patterns)

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#23]
I think this is probably the simplest thing for now, but it might be interesting to reconsider in the future and the effect on typing.

For now, this can be done before type checking, after parsing.

**Comment by vimuel** [comment]
Do you mean something in the style of Erlang or (I believe) Miranda?

**Comment by vimuel** [comment]
That is, where you can write something like
```idris
eq x x = True
```

**Comment by buggymcbugfix** [comment]
Fixed by 7721aa61
