### ISSUE TITLE
Spurious `()` in stdout

### ISSUE THREAD

**Issue by rzuckerm** [granule-project/granule#230]
I have this simple program:
```
main : () <{Stdout}>
main = toStdout "Hello, world!\n"
```

When I run this:
```console
$ gr --no-info hello_world.gr
```

I see this:
```
Hello, world!
()
```

Is there any way to get rid of the suprious `()` in the output? I am using the 0.9.4.0 of the granule compiler on Ubuntu 22.04. I installed this by unzipping the [Linux x86-64 zip file](https://github.com/granule-project/granule/releases/download/v0.9.4.0/granule-v0.9.4.0-linux_x86_64.zip) I've looked through all the options, and I don't see anyway to get rid of this.

**Comment by dorchard** [comment]
Thanks for this! What is going on here is that you are getting the input-output message on your console and then you are also getting the return output of the program- we always show the output of the program s well.
There isn't really a way of suppressing this if you are using `gr` but I can see how it would be useful not to see this! Do you want to turn this into a feature request?

**Comment by rzuckerm** [comment]
@dorchard Yes, please

**Comment by dorchard** [comment]
Maybe something like `gr --no-return-value` ?

**Comment by rzuckerm** [comment]
Yes, that would be good. Thanks!

**Comment by rzuckerm** [comment]
When #231 is merged, will there be a new release? I'd prefer to use a released version for [this docker image](https://github.com/rzuckerm/granule-docker-image) that I use in the [Sample Programs repo](https://github.com/TheRenegadeCoder/sample-programs).

**Comment by dorchard** [comment]
Sorry forgot to say that this in release https://github.com/granule-project/granule/releases/tag/v0.9.5.0!
