### ISSUE TITLE
Nested box

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#27]
```idris
flatten ||x|| = |x|
```
and

```idris
flatten |xbox| = let |x| : Int = xbox in |x|
```

should be the same.

**Comment by vimuel** [comment]
```idris
flatten ||x|| = |x|
```
is also causing issues in the desugarer

**Comment by dorchard** [comment]
This looks like it is fixed now.

**Comment by dorchard** [comment]
I don't know how this was resolved but `flatten ||x|| = |x|` should be fine, but the following should be rejected
```
flatty : forall (n : Nat=, m : Nat=) . (Int |n|) |m| -> Int |n*m|
flatty xboxbox = let |xbox| = xboxbox in let |x| = xbox in |x|
```
We need to examine whether we did something bad to allow this as a result of this issue, or just incidentally.

**Comment by dorchard** [comment]
This is resolved now and we have tests for this, e.g.,
frontend/tests/cases/negative/flatten/flattenByLet.gr
(negative)
and
StdLib/Prelude.gr 
(positive)
