### ISSUE TITLE
Subtraction not parsed properly

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#41]
```
pred : Int -> Int
pred x = x-1
Type error: stdin:2:10:
  (Int) -> Int is not equal to Int
```

**Comment by vimuel** [comment]
On the other hand, maybe we should require spaces around operators.

That way, we don't run into ambiguities with `-1`.

Further, it would allow making user-defined names like `Nat=`.

Not sure if this is good, but worth a thought.

- `this-is-a-valid-variable-name`
- `so^is&this`
- `yo*4,this+too`

Hmm. I think I take that back.

**Comment by GuiltyDolphin** [comment]
@buggymcbugfix any update on this, considering the recent changes to variable names/operator spacing?
