### ISSUE TITLE
Exhaustivity check

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#45]
I will try to work on this soonish.

This should prevent definitions as the following (it should recognise that I haven't matched on the `Nil` case):

```
head : forall a : Type, n : Nat= . (Vec a n) |1| -> a
head x = case x of |(Cons x _)| -> x
```

**Comment by vimuel** [comment]
This also ties in with irrefutable patterns.

**Comment by buggymcbugfix** [comment]
Closing this because there is already a related project entry.
