### ISSUE TITLE
Classes and records in Granule

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#48]
One can say that _type classes_ (_interfaces_ in Idris parlance) are a coeffect.

We don't have a concept for this in Granule yet, so I'm just opening this issue as a forum for discussion about this.

The way I understand type classes as a coeffect corresponds to something like this:
```agda
print : a ∈ Show -> a -> <[W]> ()
```
I think that it could be possible to have explicit instantiation with a witness if we have some sort of compile-time coeffect that says "the compiler will insert this".

If we had some awareness of _stages_ in the language, then an open class could look like this:
```agda
print : a ∈ Show -> a -> <[W]> () -- have to pass witness
```
While a closed class would perhaps conceptually resemble something like this:
```agda
print : a ∈ Show |CompileTime| -> a -> <[W]> () -- known statically
```

I also think that this can tie in somewhat with records and what people call _row polymorphism_. This is a popular and compelling feature in (amongst other MLs) Purescript ([see docs](https://leanpub.com/purescript/read#leanpub-auto-record-patterns-and-row-polymorphism)).  Let's face it: something along the lines of records is a must-have, but Haskell records suck.

However, I feel that row polymorphism is a bit ad-hoc. I wonder whether we can tie this up more nicely in a way related to classes (semantically, not concerned about syntax atm). 

An example given in the Purescript documentation:

```purescript
> showPerson { first: x, last: y } = y <> ", " <> x

> :type showPerson
forall r. { first :: String, last :: String | r } -> String
```

To me this seems artificially narrow. Why should this only work for records? A more general framework could involve something type-classy (ignoring linearity for now, there is a bit of complexity in that, I believe):

```
showPerson : p ∈ HasFirst -> p ∈ HasLast -> p -> String
```

I have been wondering wether something like the following could be a not-so-ad-hoc solution to the Haskell record problem of not allowing overlapping field names:

```haskell
class HasFirst a where
  first :: a -> String

data Foo = Bar { first :: String } deriving HasFirst
```

**TODO** There are also [Idris records](http://docs.idris-lang.org/en/latest/tutorial/typesfuns.html#records), which I will play around with.

**Comment by brendanzab** [comment]
> ```purescript
> > showPerson { first: x, last: y } = y <> ", " <> x
> :type showPerson
>
> forall r. { first :: String, last :: String | r } -> String
> ```
>
> To me this seems artificially narrow. Why should this only work for records? A more general framework could involve something type-classy (ignoring linearity for now, there is a bit of complexity in that, I believe):

You may already know this, but do note that `{ first :: String, last :: String | r }` is [actually sugar](https://pursuit.purescript.org/builtins/docs/Prim#t:Record) for `Record ( first :: String, last :: String | r )`.

Purescipt's type system is extended as follows:

```
kind ::= Type                                Kind of proper types
       | Row                                 Kind of rows
       | Symbol                              Kind of type level strings
       | kind1 -> kind2                      Type constructors

type ::= ()                                  Empty row
       | ( symbol :: type1 | type2 )         Row extension
       | symbol                              Type level strings
       | ...
```

This allows rows to be used for both extensible records, but also [effect rows](https://pursuit.purescript.org/packages/purescript-run) as well. Not sure if it has extensible variants as well, but I could envisage them being built as a library using rows as well.

Note that there are also built-in classes that describe operations on rows, for example [`Union`](https://pursuit.purescript.org/builtins/docs/Prim#t:Union), [`RowCons`](https://pursuit.purescript.org/builtins/docs/Prim#t:RowCons), etc.

**Comment by vimuel** [comment]
Thanks for this information @brendanzab. :)

**Comment by brendanzab** [comment]
Could you just make 'instance arguments' a variant of the 'implicit argument' coeffect - if you have one, that is? In my dependently typed lang I was planning to use this kind of syntax (kind of like Agda):

```
isEmpty : {a : Type} {{E : Eq a}} {{M : Monoid a}} -> a -> Bool
isEmpty {{E}} {{M}} x = E.eq x M.empty
```

I can see how that could pretty easily desugar down to coeffects though

**Comment by vimuel** [comment]
We don't have any whole-context coeffects in Granule at the moment. I like what you do in your example though. I'm also thinking about other options which would let you name instances, perhaps some marriage between ML functors and Haskell type classes.

For example you may well want to write two different `Ord` instances for `Nat`, to be able to sort things in ascending and descending order.

Or you may want to have different notions on equality, e.g. syntactic equality, vs equality after normalisation for terms.

**Comment by brendanzab** [comment]
Yeah, that's what I'm planning too - using [dependent records](https://github.com/brendanzab/pikelet/issues/2) for classes, and instance arguments. There are trade-offs ergonomically, but I feel it's the better approach. Have to watch out for the "set problem" - ie. making sure that sets or maps use the same notion of ordering or hashing before comparing/merging them. I plan to index those datatypes with the instance used to constuct them, but generative functors is another approach.

**Comment by vimuel** [comment]
Ah, great to see that you are tackling similar problems. Your project page is a trove of ideas—thanks for the link, I will definitely keep this on my radar.

**Comment by brendanzab** [comment]
No worries! We have similar ideas yes - but I was silly enough to make mine dependently typed first, so might be blocked on coeffects+effects until the research catches up, so watching Granule is super interesting to me! 😅

**Comment by buggymcbugfix** [comment]
Moving to projects.
