### ISSUE TITLE
RFC: Generalise, simplify AST/Patterns, allow user-defined operators

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#49]
# Remove Binary Operators

The idea is to treat them like normal functions. This would mean making the type checker, interpreter, etc. leaner (only removing stuff) and doing more work during parsing and lexing (with modest additions to the pretty printer). 

## Proposed Roadmap (Please Comment)

1. Define a clear set of allowable and disallowed custom operators (consider `Checker.Primitives` and the parser).
2. Adapt lexer and parser
2.1 Treat backticked prefix functions and operators the same, e.g. `` `mod` `` and `+`
2.2 Treat parenthesised operators the same as prefix functions, e.g. `mod` and `(+)`
2.3 The solution to the above should take care of operator sections, e.g. `(+1)` and `` (`mod` 2) ``
2.5 Need fixity declarations.
2.6 Think about cases like the following:
```haskell
{-# LANGUAGE PostfixOperators #-}
-- | Factorial
-- >>> (3!) -- need parens
-- 6
(!) = product . enumFromTo 2
```
3. Adapt pretty-printer.
4. Allow operators as the `Id` of a `Def` and `DataConstr`s.

# Remove Pairs
They are just an instance of a data constructor. We could have `,` as the product constructor in the StdLib. If we do this, we need to think about how this interacts with List syntax (see also #47).

**Comment by vimuel** [comment]
Dedicated pairs are gone now, although we are still treating them specially in the parser.

**Comment by buggymcbugfix** [comment]
Moving to projects.
