### ISSUE TITLE
Provide a 'top' effect annotation

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#50]
e.g.
`t <*>` which over approximates all effects (or perhaps `t <IO>`).

At the moment there is a built in `IO` constructor which does this, but then it breaks the postfix modality idea.

**Comment by vimuel** [comment]
Maybe effect classes to allow at least some control over what happens.

**Comment by vimuel** [comment]
e.g. `t <FileIO>` tells you a lot more than `t <IO>`. This seems like a good middle ground between Haskell and our current extremely fine-grained effect tracking.

**Comment by vimuel** [comment]
Or even in future if we get rid of the built-in lists, we could have `t <O, R, W, C, FileIO>` and `t <Any, FileIO>` or something like that. Or even allow ` ` to be overloaded ;) `t <O R W C FileIO>` and `t <Any FileIO>`.

**Comment by vimuel** [comment]
I'm not actually sure if effect classes are very useful in a "hostile" environment. I was hoping to distinguish between things like `FileIO`, `TermIO` and `NetIO`. But, people could e.g. do network I/O over files or the terminal as well. Effect classes would probably only be useful if we were in direct control of the hardware with no OS in between—then we could distinguish between these things.

I suppose similar considerations hold for the fine-grained effect gradings?
