### ISSUE TITLE
Improve wildcard typing

### ISSUE THREAD

**Issue by dorchard** [granule-project/granule#65]
Currently we get errors like this:
```
$ gr tests/regression/illtyped/wild2.gr 

Checking tests/regression/illtyped/wild2.gr...
Linearity error: tests/regression/illtyped/wild2.gr: :1:1:
  Linear variable `_` is never used.
Failed
```
(where wild2.gr contains `foo _ = 0`)
This indeed should be an error, but we want a better error message. Related to this but more serious is the example:
```
-- This should be ok:
isZero : Int -> Bool
isZero x = case x of 0 -> True; _ -> False
```
This should be allowed as the concrete pattern match of 0 means we use `x` exactly once, but this is not allowed at the moment due to the second pattern which is a wildcard.

This relates slightly to issue https://github.com/dorchard/granule/issues/64  but should be more to do with the role of concrete patterns with a linear guard.

**Comment by buggymcbugfix** [comment]
Should `foo _ = 0` be ok with monoshaped datatypes?

**Comment by dorchard** [comment]
This has been fixed now.
