### ISSUE TITLE
Check for name clashes with builtin primitives

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#68]
This gets accepted at the moment, even though it's already defined in the builtins.
```
data () where () : ()
```

**Comment by vimuel** [comment]
Alternatively we could just define unit in the Prelude... although that seems a bit weird.

**Comment by dorchard** [comment]
I'm not sure we can as several other built-ins use the unit type.

**Comment by dorchard** [comment]
Looks like you already fixed this!
