### ISSUE TITLE
Improve pretty printing

### ISSUE THREAD

**Issue by buggymcbugfix** [granule-project/granule#69]
The following library can print `Show` values in a more readable format:
http://hackage.haskell.org/package/pretty-show-1.7/docs/Text-Show-Pretty.html

We should use it.

**Comment by vimuel** [comment]
TIL:
```bash
$ stack build pretty-simple # In a stack project
$ stack ghci --package pretty-simple
$ ghci> import Text.Pretty.Simple (pPrint)
```
